services:
    web:
      build: .
      ports:
        - "8000:8000"
        - "8678:8678"
      volumes:
        - .:/app
      command: ["sh", "-c", "pip install debugpy -t /Users/rishichadda/tmp && python -m debugpy --wait-for-client --listen 0.0.0.8678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 8000"]